---

- name: "Gestion de usuarios en Ubuntu"
  hosts: web_servers
  become: true

  vars_files:
    - ./variables/credentials.yml
  
  tasks:
    - name: Crear el grupo developers
      group:
        name: developers
        state: present
    - name: Crear usuario admin
      user:
        name: "{{ user }}"
        password: "{{ pass }}"
        group: developers
        create_home: true
        shell: /bin/bash
        state: present
    - name: Establecer permisos para usuario
      file:
        path: "/home/{{ user }}"
        owner: "{{ user }}"
        group: developers
        mode: "0750"
        state: directory

