---
- name: Gestion de servicios
  hosts: win_servers
  gather_facts: false
  
  vars:
        data: "dato de windows"

  tasks:
    - name: "Ver variable win"
      win_debug:
        msg: "Valor de la variable data: {{ data }}"
    - name: Parar servicio audio
      ansible.windows.win_service:
        name: Audiosrv
        state: stopped
    
    - name: Rearrancar 
      ansible.windows.win_service:
        name: Audiosrv
        state: started